# noinspection undefined
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/e_shop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
    mvc:
      hiddenmethod:
        filter:
          enabled: true
  google.recaptcha:
              site: ${RECAPTCHA_SITE_KEY:test}
              secret: ${RECAPTCHA_SITE_SECRET:test}
  sql:
      init:
        mode: never
        security:
          oauth2:
            client:
              registration:
                github:
                  client-id: ${GITHUB_CLIENT:}
                  client-secret: ${GITHUB_SECRET:}
                  redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
                  scope: user:username
# noinspection undefined
jpa:

      database-platform: org.hibernate.dialect.MySQL8Dialect

      hibernate:
        ddl-auto: update
      open-in-view: false
      properties:
        hibernate:
        format_sql: true
      defer-datasource-initialization: true

    #api-key:
    #api-secret:

# noinspection undefined
thymeleaf:
      cache: false
      mode: HTML
      encoding: UTF-8
      prefix: file:src/main/resources/templates/
# noinspection undefined
resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
        server:
          port: 8080






# noinspection undefined
cloudinary:
  cloudinary.cloud-name: ${CLOUD_NAME:`pavlina`}
  cloudinary.api-key: ${API_KEY:`789253417854732`}
  cloudinary.api-secret: ${API_SECRET:`Oasdj9hyXRAjHv4eq3KZCD-DdnQ`}






