# noinspection undefined
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/e_shop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
    mvc:
      hiddenmethod:
        filter:
          enabled: true
    sql:
      init:
        mode: never
    jpa:
      # Choose either MySQL 8 or MySQL 5 below
      # For MySQL 8
      database-platform: org.hibernate.dialect.MySQL8Dialect
      #For MySQL 5
      #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
      open-in-view: false
      properties:
        hibernate:
        format_sql: true
      defer-datasource-initialization: true
    #Cloudinary Properties
    #cloudinary:
    #api-key:
    #api-secret:
    #cloud-name:
    thymeleaf:
      cache: false
      mode: HTML
      encoding: UTF-8
      prefix: file:src/main/resources/templates/
    resources: # Static resources
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
        server:
          port: 8080
  logging:
    level:
      org:
        springframework:
          security: DEBUG



# noinspection undefined
cloudinary:
  cloudinary.cloud-name: ${CLOUD_NAME:`pavlina`}
  cloudinary.api-key: ${API_KEY:`789253417854732`}
  cloudinary.api-secret: ${API_SECRET:`Oasdj9hyXRAjHv4eq3KZCD-DdnQ`}






