spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/e_shop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
      format_sql: true
    hibernate:
      ddl-auto: update
  sql:
      init:
        mode: never
  mvc:
      hiddenmethod:
        filter:
          enabled: true


logging:
    level:
      # noinspection undefined
      org.hibernate.SQL: DEBUG
      # noinspection undefined
      org.hibernate.orm.jdbc.bind: TRACE

server:
    port: 8080






